### ISSUE TITLE
Jira + Tempo Time Sheets + Exply for Task and Sub Tasks totaling. 

### ISSUE THREAD

**Issue by fjmazzeo** [sandstorm/exply-issue-tracker#1]
We currently use Jira and Tempo Time sheets.  On Friday we installed Exply Dashboards, Charts & Reports on our Jira Server.

If I have tasks and sub-tasks with hours assigned to them in tempo timesheets, can I use Exply to add the hours together and show me the total?  Does that functionality exist with Exply?

Is there someone from Exply that could have a phone or GoToMeeting conversation with me?

Thank you for your time.

**Comment by tschoeki** [comment]
Hi @fjmazzeo,

sorry for the very late response!

Regarding your question: yes, that is absolutely possible. We can also do a quick (video) call so that I can show you how to do this.

We also released Exply 4.1.0 this week! Be sure to check it out :)

Sorry again!
sunny regards
Fabian from Exply
